CREATE TYPE user_role AS ENUM ('client','staff','admin');
CREATE TYPE invoice_status AS ENUM ('unpaid','paid','overdue','refunded');
CREATE TYPE message_status AS ENUM ('open','pending','resolved');

CREATE TABLE users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, role user_role NOT NULL DEFAULT 'client', email_verified_at timestamptz, mfa_secret_ciphertext bytea, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE client_profiles (user_id uuid PRIMARY KEY REFERENCES users(id), full_name text NOT NULL, phone text, address_ciphertext bytea, tax_year integer, filing_type text, assigned_staff_id uuid REFERENCES users(id));
CREATE TABLE documents (id uuid PRIMARY KEY, client_id uuid NOT NULL REFERENCES users(id), uploaded_by uuid NOT NULL REFERENCES users(id), category text NOT NULL, display_name text NOT NULL, storage_key text UNIQUE NOT NULL, mime_type text NOT NULL, byte_size bigint NOT NULL CHECK(byte_size <= 26214400), scan_status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE document_requests (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), requested_by uuid REFERENCES users(id), category text, note text, due_at timestamptz, completed_at timestamptz);
CREATE TABLE tax_returns (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), tax_year integer NOT NULL, filing_type text, status text NOT NULL, status_updated_by uuid REFERENCES users(id), status_updated_at timestamptz DEFAULT now());
CREATE TABLE tax_status_events (id uuid PRIMARY KEY, tax_return_id uuid REFERENCES tax_returns(id), status text NOT NULL, note text, created_by uuid REFERENCES users(id), created_at timestamptz DEFAULT now());
CREATE TABLE message_threads (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), subject text NOT NULL, status message_status DEFAULT 'open', created_at timestamptz DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY, thread_id uuid REFERENCES message_threads(id), sender_id uuid REFERENCES users(id), body_ciphertext bytea NOT NULL, read_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE message_attachments (message_id uuid REFERENCES messages(id), document_id uuid REFERENCES documents(id), PRIMARY KEY(message_id,document_id));
CREATE TABLE invoices (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), number text UNIQUE NOT NULL, amount_cents integer NOT NULL, currency char(3) DEFAULT 'USD', status invoice_status DEFAULT 'unpaid', stripe_payment_intent_id text, due_at timestamptz, paid_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE client_tasks (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), title text NOT NULL, due_at timestamptz, completed_at timestamptz, created_by uuid REFERENCES users(id));
CREATE TABLE internal_notes (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), author_id uuid REFERENCES users(id), body_ciphertext bytea NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE irs_authorizations (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), form_type text CHECK(form_type IN ('8821','2848')), document_id uuid REFERENCES documents(id), verified_by uuid REFERENCES users(id), verified_at timestamptz, expires_at timestamptz);
CREATE TABLE service_requests (id uuid PRIMARY KEY, client_id uuid REFERENCES users(id), kind text NOT NULL, payload_ciphertext bytea, status text DEFAULT 'new', created_at timestamptz DEFAULT now());
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, actor_id uuid REFERENCES users(id), client_id uuid REFERENCES users(id), action text NOT NULL, entity_type text, entity_id text, ip_hash text, user_agent text, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_client_time ON audit_logs(client_id,created_at DESC);
CREATE INDEX documents_client_time ON documents(client_id,created_at DESC);
