import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Clock, FileText, Landmark, LockKeyhole, ShieldCheck, TrendingUp, UsersRound } from "lucide-react";

const services=[
 {n:"Tax strategy & preparation",d:"Personal and business returns, planned proactively—not just filed.",i:"01",Icon:Landmark},
 {n:"Monthly bookkeeping",d:"Clean books, useful reporting, and a close you can count on.",i:"02",Icon:FileText},
 {n:"Payroll & compliance",d:"Dependable payroll, filings, and support for your growing team.",i:"03",Icon:UsersRound},
 {n:"Advisory & CFO services",d:"Clear financial insight for the decisions that move you forward.",i:"04",Icon:TrendingUp}
];
export function HomePage(){return <>
 <section className="hero"><div className="eyebrow"><span/> ACCOUNTING, WITH CLARITY</div><h1>Numbers handled.<br/><em>Decisions made easier.</em></h1><p>Tax, bookkeeping, and advisory services for people and businesses who expect more from their accountant.</p><div className="hero-buttons"><Link className="btn" href="/contact">Start with Alliance <ArrowRight/></Link><Link className="btn outline" href="/contact"><CalendarDays/> Book a consultation</Link></div><div className="trust-row"><span><ShieldCheck/> Secure client portal</span><span><Check/> Year-round support</span><span><Check/> Remote, nationwide service</span></div>
 <div className="hero-card"><div className="hc-top"><span>SECURE CLIENT PORTAL</span><span className="secure"><LockKeyhole/> Protected</span></div><div className="hc-person"><div className="avatar">AA</div><div><b>Your finances, organized.</b><small>Documents, messages, invoices, and status.</small></div></div><div className="progress"><div className="prog-title"><b>Tax preparation workflow</b><span>Clear</span></div><div className="bar"><i/></div><div className="steps"><span className="done"><Check/></span><i/><span className="done"><Check/></span><i/><span className="current">3</span><i/><span>4</span></div><div className="step-labels"><span>Documents</span><span>Review</span><span>Preparing</span><span>Approval</span></div></div><div className="hc-note"><Clock/><div><b>Know what comes next</b><small>Receive secure updates from your tax team.</small></div></div></div></section>
 <section className="cred"><span>TRUSTED SUPPORT FOR</span><b>Individuals</b><b>Small businesses</b><b>Independent professionals</b><b>Growing teams</b></section>
 <section className="intro"><div><div className="eyebrow"><span/> WHAT WE DO</div><h2>Expertise that fits<br/>the way you work.</h2></div><p>We bring the diligence of a traditional firm together with the responsiveness and technology you expect today.</p></section>
 <section className="services">{services.map(({n,d,i,Icon})=><article key={i}><div className="service-num">{i}</div><div className="service-icon"><Icon/></div><h3>{n}</h3><p>{d}</p><Link href="/services">Explore service <ArrowRight/></Link></article>)}</section>
 <section className="statement"><div className="statement-art"><div className="building">{Array.from({length:6}).map((_,i)=><span key={i}/>)}</div><div className="quote">“Alliance gave us the confidence to stop looking backward—and start planning forward.”<small>— MAYA R., FOUNDER &amp; CLIENT</small></div></div><div className="statement-copy"><div className="eyebrow"><span/> WHY ALLIANCE</div><h2>A steady partner<br/>in every season.</h2><p>Financial questions rarely arrive on schedule. That’s why our clients get a dedicated team, clear next steps, and support that extends well beyond tax day.</p><ul><li><Check/> Advice tailored to your whole financial picture</li><li><Check/> Transparent scope and predictable pricing</li><li><Check/> Secure, simple collaboration from anywhere</li></ul><Link className="btn" href="/about">Meet our team <ArrowRight/></Link></div></section>
 <section className="cta"><div><div className="eyebrow light"><span/> LET’S GET STARTED</div><h2>Your finances deserve<br/>a clearer path forward.</h2></div><div><p>Tell us what you’re working toward. We’ll show you how we can help.</p><Link className="btn gold" href="/contact">Book a consultation <ArrowRight/></Link></div></section>
 </>}
